# Generated by Django 4.1.5 on 2023-02-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('dataglen', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('active', models.BooleanField(default=True)),
                ('allowGroups', models.BooleanField(default=True)),
                ('ownerViewURL', models.CharField(max_length=50)),
                ('employeeViewURL', models.CharField(max_length=50)),
                ('groupViewURL', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('client_view', 'Allowed to access client view of this dashboard'), ('employee_view', 'Allowed to access employee view of this dashboard'), ('group_view', 'Allowed to access group view of this dashboard'), ('can_create_groups', 'This employee is allowed to create groups of this dashboard')),
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='DataglenClient',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('clientWebsite', models.URLField()),
                ('clientLogo', models.URLField(blank=True, null=True)),
                ('clientMobileLogo', models.URLField(blank=True, null=True)),
                ('clientDomain', models.CharField(blank=True, max_length=50, null=True)),
                ('clientContactAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('canCreateGroups', models.BooleanField(default=False)),
                ('webdynClient', models.BooleanField(default=False)),
                ('clientDashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataglen_clients', to='dashboards.dashboard')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='DataglenGroup',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('groupLogo', models.URLField(blank=True, null=True)),
                ('groupMobileLogo', models.URLField(blank=True, null=True)),
                ('groupClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataglen_groups', to='dashboards.dataglenclient')),
                ('groupPermissions', models.ManyToManyField(blank=True, null=True, related_name='dataglen_groups', to='auth.permission')),
                ('groupSensors', models.ManyToManyField(blank=True, null=True, related_name='dataglen_groups', to='dataglen.sensor')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
    ]
