# Generated by Django 4.1.5 on 2023-02-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solarrms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataglen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('alert_date', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('1', 'DAILY'), ('7', 'WEEKLY'), ('30', 'MONTHLY')], max_length=50)),
                ('recurring', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('time', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=50)),
                ('associated_devices', models.CharField(choices=[('AJB', 'AJB'), ('INVERTER', 'INVERTER'), ('ENERGY METER', 'ENERGY_METER'), ('DATA_LOGGER', 'DATA_LOGGER'), ('PLANT', 'PLANT'), ('ALL', 'ALL')], max_length=50)),
            ],
            options={
                'unique_together': {('name', 'frequency', 'recurring', 'time', 'associated_devices')},
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('scheduled_start_date', models.DateTimeField()),
                ('scheduled_closing_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('RESCHEDULED', 'RESCHEDULED'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('LOCKED', 'LOCKED')], max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=50)),
                ('is_custom', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='users', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', related_query_name='cycles', to='oandmmanager.cycle')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='tasks', to='oandmmanager.tasks')),
            ],
            options={
                'unique_together': {('cycle', 'task', 'scheduled_start_date', 'scheduled_closing_date')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BinaryField(default=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', related_query_name='sensors', to='dataglen.sensor')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_associations', related_query_name='task_associations', to='oandmmanager.taskitem')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='30', max_length=2)),
                ('sd', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=2)),
                ('alert_date', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='22', max_length=2)),
                ('associated_tasks', models.ManyToManyField(to='oandmmanager.tasks')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_and_m_preferences', related_query_name='o_and_m_preferences', to='solarrms.solarplant')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_and_m_cycles', related_query_name='o_and_m_cycles', to='oandmmanager.preferences'),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('preferences', 'start_date', 'end_date')},
        ),
    ]
