# Generated by Django 4.1.5 on 2023-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('packaging_function_path', models.CharField(blank=True, help_text='A function that packages the raw data', max_length=100, null=True)),
                ('widget_id', models.IntegerField()),
                ('features', models.ManyToManyField(related_name='widgets', to='features.feature')),
            ],
        ),
    ]
