# Generated by Django 4.1.5 on 2023-02-09 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solarrms', '0001_initial'),
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('O&M_MANAGER', 'O&M_MANAGER'), ('SITE_ENGINEER', 'SITE_ENGINEER'), ('CLIENT_CEO', 'CLIENT_CEO'), ('CLIENT_O&M_MANAGER', 'CLIENT_O&M_MANAGER'), ('CLIENT_SITE_ENGINEER', 'CLIENT_SITE_ENGINEER')], max_length=100)),
                ('daily_report', models.BooleanField(default=False)),
                ('enable_alerts', models.BooleanField(default=False)),
                ('account_suspended', models.BooleanField(default=False)),
                ('enable_preference_edit', models.BooleanField(default=False)),
                ('gateway_alerts_notifications', models.BooleanField(default=False)),
                ('inverters_alerts_notifications', models.BooleanField(default=False)),
                ('other_alerts', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False, help_text='Is SMS alerts enabled for this user.')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number on which sms alerts should be sent.', max_length=15, null=True)),
                ('viewOnly', models.BooleanField(default=False, help_text='If downloadable link should be enabled or not.')),
                ('dg_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_client', related_query_name='dg_client', to='dashboards.dataglenclient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', related_query_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolePlantsAlertsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.ManyToManyField(related_name='alerts_users_preferences', related_query_name='alerts_users_preferences', to='solarrms.solarplant')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_preferences_plants', related_query_name='alerts_preferences_plants', to='dgusers.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='AlertsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GATEWAY_POWER_OFF', 'GATEWAY_POWER_OFF'), ('GATEWAY_DISCONNECTED', 'GATEWAY_DISCONNECTED'), ('INVERTERS_DISCONNECTED', 'INVERTERS_DISCONNECTED'), ('AJBS_DISCONNECTED', 'AJBS_DISCONNECTED'), ('INVERTERS_NOT_GENERATING', 'INVERTERS_NOT_GENERATING'), ('INVERTERS_ALARMS', 'INVERTERS_ALARMS'), ('AJB_STRING_CURRENT_ZERO_ALARM', 'AJB_STRING_CURRENT_ZERO_ALARM'), ('PANEL_CLEANING', 'PANEL_CLEANING'), ('INVERTERS_UNDERPERFORMING', 'INVERTERS_UNDERPERFORMING'), ('MPPT_UNDERPERFORMING', 'MPPT_UNDERPERFORMING'), ('AJB_UNDERPERFORMING', 'AJB_UNDERPERFORMING'), ('CUSTOM_TICKET', 'CUSTOM_TICKET')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('threshold_applicable', models.BooleanField(default=False)),
                ('threshold_value', models.FloatField(default=10)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('email_aggregation_minutes', models.IntegerField(default=120)),
                ('sms_aggregation_minutes', models.IntegerField(default=120)),
                ('emails_count', models.IntegerField(default=0)),
                ('sms_count', models.IntegerField(default=0)),
                ('last_email', models.DateTimeField(blank=True, null=True)),
                ('last_sms', models.DateTimeField(blank=True, null=True)),
                ('alert_on_close', models.BooleanField(default=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_preferences', related_query_name='alerts_preferences', to='dgusers.userrole')),
            ],
            options={
                'unique_together': {('user_role', 'event_type')},
            },
        ),
    ]
