# Generated by Django 4.1.5 on 2023-02-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataglen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidUID',
            fields=[
                ('UID', models.CharField(help_text='Valid UID of IoELab Kits provided by vendors', max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(help_text='Valid UID of IoELab Kits provided by vendors', max_length=12)),
                ('emailid', models.EmailField(help_text='email-id for the invitation to be sent', max_length=100)),
                ('status', models.PositiveSmallIntegerField(default=0, help_text='status of the invitation: 0-Invitation sent, 1-Invitation accepted, 2-Invitation expired, 3-Device validated, ownership changed, 4-De-registration executed')),
                ('inviteTime', models.DateTimeField(auto_now_add=True)),
                ('default_load', models.BooleanField(blank=True, default=False)),
                ('invitee', models.ForeignKey(blank=True, help_text='invitee name', on_delete=django.db.models.deletion.CASCADE, related_name='ioeinvites_sent', related_query_name='ioeinvites_sent', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(help_text='IoELab invite for the source', on_delete=django.db.models.deletion.CASCADE, related_name='invite', related_query_name='invite', to='dataglen.sensor', to_field='sourceKey')),
            ],
            options={
                'unique_together': {('UID', 'emailid', 'status')},
            },
        ),
    ]
