# Generated by Django 4.1.5 on 2023-02-08 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('installations_limit', models.IntegerField(default=1)),
                ('customer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_key', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('installation_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('install_ts', models.DateTimeField(default=datetime.datetime(2023, 2, 8, 12, 21, 52, 186144))),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
                ('active_installation', models.BooleanField(default=False)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', related_query_name='installations', to='license.license')),
            ],
        ),
    ]
